version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    
    schedule:
      interval: "weekly"

    commit-message:
      prefix: "chore(deps)"

    groups:
      deps-version-updates:
        applies-to: "version-updates"
